name: build

on:
  workflow_call:
    outputs:
      version:
        description: The generated version for the build
        value: ${{ jobs.build.outputs.version }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.generate_version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-tags: true
      - name: Print info
        run: |
          echo "::notice::Repository: $GITHUB_REPOSITORY"
          echo "::notice::Latest tag: $(git describe --tags $(git rev-list --tags --max-count=1))"
      - name: Generate version
        id: generate_version
        run: |
          echo "::notice::Generating version based on latest tag and commit SHA"
          BUILD_TIMESTAMP=$(date -u +"%Y%m%d%H%M%S")
          LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
          COMMIT_SHA=$(git rev-parse --short HEAD)
          if [ -z "$LATEST_TAG" ]; then
            VERSION="0.1.0-${BUILD_TIMESTAMP}-${COMMIT_SHA}"
          else
            VERSION="${LATEST_TAG}-${BUILD_TIMESTAMP}-${COMMIT_SHA}"
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "::notice::Generated version: $VERSION"
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
      - name: Build
        uses: tdpauw/reusable_workflows/.github/actions/build@main
        with:
          version: ${{ steps.generate_version.outputs.version }}
      - name: Build Lead Time
        shell: bash
        run: |
          COMMIT=$(git log --pretty=format:"%h %s %an %ad" --date=relative)
          COMMIT_TS="$(git log -1 --format=%cI)"
          END_TS="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"

          echo "::notice::Branch: $GITHUB_REF_NAME"
          echo "::notice::$(git log -1 --pretty=format:"%h %s %an %ad" --date=relative)"
          echo "::notice::Commit timestamp  : $COMMIT_TS"
          echo "::notice::Build finish time : $END_TS"

          # Convert timestamps to epoch seconds
          commit_epoch=$(date -d "$COMMIT_TS" +"%s")
          end_epoch=$(date -d "$END_TS" +"%s")

          lead_time_in_seconds=$((end_epoch - commit_epoch))
          echo "::notice::Build Lead time (seconds): $lead_time_in_seconds"


          printf -v lead_time_human "%02dh %02dm %02ds" \
            $((lead_time_in_seconds/3600)) \
            $(((lead_time_in_seconds%3600)/60)) \
            $((lead_time_in_seconds%60))
          echo "::notice::Build Lead time (human): $lead_time_human"

          echo "$COMMIT" >> $GITHUB_STEP_SUMMARY
          echo "Build Lead Time: $lead_time_in_seconds seconds ($lead_time_human)" >> $GITHUB_STEP_SUMMARY
