name: build

on:
  workflow_call:
    outputs:
      version:
        description: The generated version for the build
        value: ${{ jobs.build.outputs.version }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.generate_version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-tags: true
      - name: Print info
        run: |
          echo "::notice::Repository: $GITHUB_REPOSITORY"
          echo "::notice::Latest tag: $(git describe --tags $(git rev-list --tags --max-count=1))"
      - name: Generate version
        id: generate_version
        run: |
          echo "::notice::Generating version based on latest tag and commit SHA"
          BUILD_TIMESTAMP=$(date -u +"%Y%m%d%H%M%S")
          LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
          COMMIT_SHA=$(git rev-parse --short HEAD)
          if [ -z "$LATEST_TAG" ]; then
            VERSION="0.1.0-${BUILD_TIMESTAMP}-${COMMIT_SHA}"
          else
            VERSION="${LATEST_TAG}-${BUILD_TIMESTAMP}-${COMMIT_SHA}"
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "::notice::Generated version: $VERSION"
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
      - name: Build
        uses: tdpauw/reusable_workflows/.github/actions/build@main
        with:
          version: ${{ steps.generate_version.outputs.version }}
