name: pipeline
on:
  workflow_call:
    inputs:
      final_environment:
        description: The final environment to deploy to (e.g., staging, production)
        type: string
        default: production
      skip_acceptance_tests:
        description: Whether to skip the acceptance tests stage
        type: boolean
        default: false

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit

  deploy_to_staging:
    if: ${{ !failure() && !cancelled() && github.ref == 'refs/heads/main' }}
    needs: [build]
    uses: ./.github/workflows/deploy.yml
    with:
      version: ${{ needs.build.outputs.version }}
      environment: staging
    secrets: inherit
    
  test_on_staging:
    if: ${{ !failure() && !cancelled() && github.ref == 'refs/heads/main' && inputs.final_environment != 'staging'}}
    needs: [deploy_to_staging]
    uses: ./.github/workflows/acceptance_tests.yml
    with:
      version: ${{ needs.deploy_to_staging.outputs.version }}
      environment: staging
      skip_stage: ${{ inputs.skip_acceptance_tests }}
    secrets: inherit

  deploy_to_production:
    if: ${{ !failure() && !cancelled() && inputs.final_environment != 'staging' }}
    needs: [test_on_staging]
    uses: ./.github/workflows/deploy.yml
    with:
      version: ${{ needs.test_on_staging.outputs.version }}
      environment: production
    secrets: inherit
