name: pipeline
on:
  workflow_call:
    inputs:
      final_environment:
        description: The final environment to deploy to (e.g., staging, production)
        type: string
        default: production

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit

  deploy_to_staging:
    if: ${{ !failure() && !cancelled() && github.ref == 'refs/heads/main' }}
    needs: [build]
    uses: ./.github/workflows/deploy.yml
    with:
      version: ${{ needs.build.outputs.version }}
      environment: staging
    secrets: inherit
    
  test_on_staging:
    name: Test on Staging
    if: ${{ !failure() && !cancelled() }}
    environment: staging
    needs: [deploy_to_staging]
    runs-on: ubuntu-latest
    outputs:
      version: ${{ needs.deploy_to_staging.outputs.version }}
    steps:
    - name: Checkout
      uses: actions/checkout@v6
    - name: Tests
      run: make test version=${{ needs.deploy_to_staging.outputs.version }}

  deploy_to_production:
    if: ${{ inputs.final_environment != 'staging' && !failure() && !cancelled() }}
    needs: [test_on_staging]
    uses: ./.github/workflows/deploy.yml
    with:
      version: ${{ needs.test_on_staging.outputs.version }}
      environment: production
    secrets: inherit
