name: pipeline
on:
  workflow_call:

jobs:
  build:
    uses: ./.github/workflows/build.yml

  deploy_to_dev:
    if: ${{ !failure() && !cancelled() && github.ref == 'refs/heads/main' }}
    environment: development
    needs: [build]
    runs-on: ubuntu-latest
    outputs:
      version: ${{ needs.build.outputs.version }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Deploy
      id: deploy
      run: make deploy env=staging version=${{needs.build.outputs.version}}
  
  test_on_dev:
    if: ${{ !failure() && !cancelled() }}
    environment: development
    needs: [deploy_to_dev]
    runs-on: ubuntu-latest
    outputs:
      version: ${{ needs.deploy_to_dev.outputs.version }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version-file: package.json
    - name: Tests
      run: make test

  deploy_to_production:
    environment: production
    needs: [test_on_dev]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Deploy
      run: make deploy env=production version=${{needs.test_on_dev.outputs.version}}
